---
title: 'Sequence assembly'
teaching: 10
exercises: 30
---

Sequence assembly means the alignment and merging of reads in order to reconstruct the original sequence. The assembly of a genome from short sequencing reads can take a while. We will therefore run this process only for two genomes.

::::::::::::::::::::::::::::::::::::::: objectives

- Understand differences between assembly methods
- Assemble the short reads

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::: questions

- How can the information in the sequencing reads be reduced?
- What are the different methods for assembly?

::::::::::::::::::::::::::::::::::::::::::::::::::


## Sequence assembly

The assembler we will run is [SKESA](https://github.com/ncbi/SKESA). SKESA generates a final assembly from multiple kmers. A list of kmers is automatically selected by SKESA using the maximum read length of the input data, and each individual kmer contributes to the final assembly. If desired, the lengths of kmers can be specified with the --kmer and --steps flags which will adjust automatic kmer selection.

## Assembly

Because assembly of each genome might take a couple of hours, we will run all assemblies in a loop overnight. It is important to run them within the screen session or else the process will be terminated if we disconnect from the machine.

Preparation

```bash
$ mkdir ~/molepi/results/assembly
$ cd ~/molepi/data/trimmed_fastq
```

To run SKESA we will use the skesa command with a number of option that we will explore later on. We can start the loop with the assemblies with: 

```bash
$ for sample in ERR029206 ERR029207
do
skesa \
--cores 2 \
--memory 8 \
--fastq "${sample}"_1.fastq.gz_trim.fastq "${sample}"_2.fastq.gz_trim.fastq 1> ../../results/assembly/"${sample}".fasta
done
```

A non-quoted backslash, `\` is used as an escape character in Bash. It preserves the literal value of the next character that follows, with the exception of newline. This means that the back slash starts a new line without starting a new command - we only add it for better readability.

The assembly should take about 2-3 minutes per genome, using 2 cores and 8 GB of memory. 

## Downloading the missing assemblies

If you haven't assembled all samples, download the finished contigs to your computer and decompress them. They will decompress in a folder called `assembly`, so one solution is to rename the assembly folder you already have to something else:

```bash
cd ~/molepi/results
mv assembly partial_assembly
wget https://github.com/lguy/course-microbial-genomics/raw/main/episodes/files/assemblies.tar.gz .
tar xvzf assemblies.tar.gz
ls assembly
```

```output
ERR026473.fasta ERR026478.fasta ERR026482.fasta ERR029207.fasta
ERR026474.fasta ERR026481.fasta ERR029206.fasta
```

:::::::::::::::::::::::::::::::::::::::  challenge

## Challenge: What do the command line parameters of SKESA mean??

Find out a) the version of SKESA you are using and b) what the used command line parameters mean.

Hint:

```
$ skesa -h
```

prints the 'help'

:::::::::::::::  solution

## Solution

```output
$ skesa -h
..
General options:
-h [ --help ]                 Produce help message
-v [ --version ]              Print version
..
--cores arg (=0)              Number of cores to use (default all) [integer]
--memory arg (=32)            Memory available (GB, only for sorted counter)
..  
--fastq arg                   Input fastq file(s) (could be used multiple times for different runs) [string]
..
..
```

:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::  challenge

## Exercise: How many contigs were generated by SKESA??

Find out how many contigs there are in the *M. tuberculosis* isolates. 

:::::::::::::::  solution

## Solution

```bash
assembly-stats ERR026473.fasta
```

```output
stats for ERR029206.fasta
sum = 4233864, n = 451, ave = 9387.73, largest = 70968
N50 = 20633, n = 68
N60 = 16723, n = 91
N70 = 13473, n = 120
N80 = 9592, n = 157
N90 = 5883, n = 213
N100 = 200, n = 451
N_count = 0
Gaps = 0
```

:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::



:::::::::::::::::::::::::::::::::::::::: keypoints

- Assembly is a process which aligns and merges fragments from a longer DNA sequence in order to reconstruct the original sequence.
- k-mers are short fragments of DNA of length k

::::::::::::::::::::::::::::::::::::::::::::::::::

